### ISSUE TITLE
Valves & Hydrants - Update Wiki Page to be current with Milestone

### ISSUE THREAD

**Issue by slmessier** [JMurk/Valve_Hydrant_Mobile_Issues#74]
**Please update the COB EXT wiki page after deployment:**
- [x] Scott to coordinate write/read access to Wiki
- [ ] Yousif to update wiki directly as needed & send email notification of update to Jun, CC scott
- [ ] Jun will QC/Review updated information & coordinate with Yousif / Scott for any potential revision.

WIKI URL - https://github.com/kcigeospatial/CityOfBaltimore/wiki/Ext-Development
